### ISSUE TITLE
Select disease from a menu with all the diseases

### ISSUE THREAD

**Issue by jonsv89** [inab/disease_perception#4]
Add a drop-down tab that allows the selection of the disease of interest

**Comment by jmfernandez** [comment]
Since commit 69ce16ec92edb5898fa9e561d86bb029554f158d it is possible to select a disease by typing a substring of its name, using the down arrow and pressing enter (or clicking on the suggestion).

Also, since commit 47a131a93c1c047ea4ec7c3e4c89e848641772b3, when you place the mouse over a disease group from the legend, it is shown a new sublegend with all the diseases of that disease group. Those diseases can be clicked, in order to select them (unless the disease was filtered out by the chosen filtering criteria).

Last, since commit 793ed5f66b2957113d37e84ca3ec98e2c0b4d000, when you click on a disease group from the legend, all the diseases from the group which are available with the filtering criteria, even if they are not visible, are selected.
